// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0MAxYuKaWT45Fasl5TQw1YumOT-gKaUI',
    appId: '1:298140799351:web:a9d4c7d1d02363065c5172',
    messagingSenderId: '298140799351',
    projectId: 'travo-app-12f4b',
    authDomain: 'travo-app-12f4b.firebaseapp.com',
    storageBucket: 'travo-app-12f4b.appspot.com',
    measurementId: 'G-4HR8B2PXTZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC73TsWVWz6PM3qtjDb6LwDr0M8bR4G2qU',
    appId: '1:298140799351:android:2ed43c3bc94a8f855c5172',
    messagingSenderId: '298140799351',
    projectId: 'travo-app-12f4b',
    storageBucket: 'travo-app-12f4b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDl4HWNCo9jd5uBiPneUYA0nTtMVtEOht4',
    appId: '1:298140799351:ios:0bcc4f1da09be8245c5172',
    messagingSenderId: '298140799351',
    projectId: 'travo-app-12f4b',
    storageBucket: 'travo-app-12f4b.appspot.com',
    iosClientId:
        '298140799351-bep6gl79jlo9kh2tgh1p3s4brvj1i96t.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDl4HWNCo9jd5uBiPneUYA0nTtMVtEOht4',
    appId: '1:298140799351:ios:0bcc4f1da09be8245c5172',
    messagingSenderId: '298140799351',
    projectId: 'travo-app-12f4b',
    storageBucket: 'travo-app-12f4b.appspot.com',
    iosClientId:
        '298140799351-bep6gl79jlo9kh2tgh1p3s4brvj1i96t.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelApp',
  );
}
